name: Footwashermedia
favicon: null
layout_spectrum: 0.5063086168374866
typography_spectrum: 0.3107198649086058
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b61a01'
    - '#767676'
    - '#c0c0c0'
  brandStrength: 0.23278285353444517
  lightness: 0.7777859647758305
  saturation: 0.8272700088564306
  rhythmicContrast: 0.48381271911785007
purpose: []
